name: Snyk Security
on: 
  push:
    branches: ['*']
  pull_request:
    branches: ['*']  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: b8696851-c357-4814-b572-a1456dabdf0b
          
