name: Snyk Security
on: 
  push:
    branches: ['*']
  pull_request:
    branches: ['*']  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: 239f7ada-30f8-47b7-904e-f3cf7fec5719
        with:
          args: --sarif-file-output=snyk.sarif
      #- name: Snyk IaC test and report
      #  run: snyk iac test --report # || true
      #- name: Build a Docker image
      #  run: docker build -t snyk/snyk:alpine .
      #- name: Snyk Container monitor
      #  run: snyk container monitor snyk/snyk:alpine --file=Dockerfile

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif
